spring:
  application:
    name: blog-manage-service-provider

  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: liyun
    password: liyun

  mvc:
    servlet:
      load-on-startup: 1

logging:
  file:
    path: /blog_manage/log
  level:
    root: info

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

