server:
  port: 80 # 端口

spring:
  application:
    name: gateway-server # 应用名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 利用微服务名进行路由
          lower-case-service-id: true

      routes:
        - id: picture-manage-01
          uri: lb://blog-picture-manage-service-provider
          order: 0
          predicates:
            - Path=/admin/picture/**,/picture/**

        - id: blog-admin-consumer-01
          uri: lb://blog-manage-service-consumer
          order: 1
          predicates:
            - Path=/**



# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://localhost:7001/eureka/