server:
  port: 8011


spring:
  application:
    name: blog-type-manage-service-provider

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:templates/
    suffix: .html

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: liyun
    password: liyun
  mvc:
    servlet:
      load-on-startup: 1



logging:
  file:
    path: log
  level:
    root: info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


