server:
  port: 8031

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: blog-picture-manage-service-provider

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: liyun
    password: liyun

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  file:
    path: log
  level:
    root: info


